### ISSUE TITLE
IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by denkv** [dice-group/ldcbench#59]
```
 	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:61)
 	at org.dice_research.ldcbench.benchmark.DataGenerator.init(DataGenerator.java:237)
 	at org.dice_research.ldcbench.generate.RandomRDF.getBarabasiRDFum(RandomRDF.java:324)
 	at org.dice_research.ldcbench.generate.RandomRDF.generateGraph(RandomRDF.java:537)
 	at org.dice_research.ldcbench.generate.RandomRDF.getOneNodeLinks(RandomRDF.java:235)
 	at java.base/java.util.Random.nextInt(Random.java:388)
 	at org.dice_research.ldcbench.generate.RandomRDF.weightedSampleWithoutReplacementOhneaw(RandomRDF.java:124)
 java.lang.IllegalArgumentException: bound must be positive
```

**Comment by abdoudesouki** [comment]
Could you give me the parameters, seed, number of nodes and degree?
